name: Generate Release Candidate Artifacts

on:
  workflow_dispatch:
    inputs:
      commit:
        description: Full Git commit SHA to evaluate and build release candidates from
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  create-candidates:
    uses: synapptech-devops/pipelines/.github/workflows/create-release-candidates-from-main.yml@v1
    with:
      pipeline_ref: main
      commit: ${{ inputs.commit }}
    secrets:
      PIPELINE_TOKEN: ${{ secrets.PIPELINE_TOKEN }}
